src/NDC/BlogBundle/Entity/Comment.php
<?php

namespace NDC\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use NDC\UserBundle\Entity\User;
use Symfony\Component\Validator\Constraints as Assert;
use NDC\BlogBundle\Validator\Constraints as NDCAssert;

/**
 * Comment
 */
class Comment
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     * @Assert\NotBlank(
     *     message="Le champ nom est vide."
     *  )
     *  @Assert\Length(
     *     max = "50",
     *     maxMessage = "Le nom ne doit pas dépasser {{ limit }} caractères."
     * )
     * @NDCAssert\AllowedUsername(
     *     message="Ce nom est réservé."
     * )
     */
    private $username;

    /**
     * @var string
     * @Assert\NotBlank(
     *     message="Le champ email est vide."
     *  )
     * @Assert\Email(
     *     message = "'{{ value }}' n'est pas un email valide."
     * )
     * @NDCAssert\AllowedUsername(
     *     field="email",
     *     message="Cette adresse mail est réservée."
     * )
     */
    private $email;

    /**
     * @var string
     * @Assert\NotBlank(
     *     message="Le champ message est vide."
     *  )
     *  @Assert\Length(
     *     min = "5",
     *     max = "1500",
     *     minMessage = "Le message doit faire {{ limit }} caractères minimum.",
     *     maxMessage = "Le message ne doit pas dépasser {{ limit }} caractères."
     * )
     */
    private $message;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \NDC\BlogBundle\Entity\Article
     */
    private $article;

    /**
     * @var boolean
     */
    private $isRegistered;

    public function __construct(Article $article = null, User $user = null)
    {
        $this->article = $article;
        $this->isRegistered = false;

        if($user != null){
            $this->username = $user->getUsername();
            $this->email = $user->getEmail();
        }
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get username
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return Comment
     */
    public function setUsername($username)
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Comment
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    public function getMd5()
    {
        return md5(strtolower(trim($this->email)));
    }

    public function getIdentifier()
    {
        return abs(crc32($this->email));
    }

    /**
     * Get message
     *
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Set message
     *
     * @param string $message
     * @return Comment
     */
    public function setMessage($message)
    {
        $this->message = $message;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Comment
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get article
     *
     * @return \NDC\BlogBundle\Entity\Article
     */
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * Set article
     *
     * @param \NDC\BlogBundle\Entity\Article $article
     * @return Comment
     */
    public function setArticle(\NDC\BlogBundle\Entity\Article $article = null)
    {
        $this->article = $article;

        return $this;
    }

    /**
     * Get isRegistered
     *
     * @return boolean
     */
    public function getIsRegistered()
    {
        return $this->isRegistered;
    }

    /**
     * Set isRegistered
     *
     * @param boolean $isRegistered
     * @return Comment
     */
    public function setIsRegistered($isRegistered)
    {
        $this->isRegistered = $isRegistered;

        return $this;
    }
}

src/NDC/BlogBundle/Entity/Image.php
<?php

namespace NDC\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Image
 */
class Image
{
    /**
     * @var integer
     */
    private $id;

    private $file;

    /**
     * @var string
     */
    private $path;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $file
     */
    public function setFile($file)
    {
        $this->file = $file;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param mixed $file
     */
    public function setUpload($file)
    {
        $this->file = $file;
    }

    /**
     * @return mixed
     */
    public function getUpload()
    {
        return $this->file;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    public function getWebPath()
    {
        return substr($this->path, strpos($this->path, 'app/../htdocs/') + 14);
    }

    public function getFileName()
    {
        return substr($this->path, strrpos($this->path, '/') +1);
    }

    /**
     * Set path
     *
     * @param string $path
     * @return Image
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }
}

src/NDC/BlogBundle/Form/ImageType.php
<?php

namespace NDC\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ImageType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file', 'file')
            ->add('Enregistrer', 'submit')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'NDC\BlogBundle\Entity\Image'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'ndc_blogbundle_image';
    }
}

src/NDC/BlogBundle/Controller/BlogController.php
<?php


namespace NDC\BlogBundle\Controller;

use NDC\AnalyticsBundle\Entity\View;
use NDC\BlogBundle\Entity\Article;
use NDC\BlogBundle\Entity\Comment;
use NDC\BlogBundle\Entity\CommentMonitoring;
use NDC\BlogBundle\Entity\Contact;
use NDC\BlogBundle\Entity\Demo;
use NDC\BlogBundle\Form\CommentType;

use NDC\BlogBundle\Form\ContactType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Doctrine\ORM\EntityManager;
use Knp\Component\Pager\Paginator;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpFoundation\Response;

class BlogController extends Controller
{
    /**
     * @var EntityManager
     */
    private $em;

    /**
     * @var Paginator
     */
    private $paginator;

    /**
     * @Template
     */
    public function indexAction(Request $request, $page)
    {
        $articles = $this->paginator->paginate(
            $this->em->getRepository('NDCBlogBundle:Article')->queryAllPublished(),
            $page,
            8
        );

        return array(
            'articles' => $articles,
        );
    }

    /**
     * @Template
     */
    public function articleAction($category, Article $article, $slug, Request $request)
    {
        // Check if readable
        $this->isArticleReadable($article);

        // Check slug
        if($article->getSlug() != $slug)
            return $this->redirect($this->generateUrl('blog_article', array('id'=>$article->getId(), 'category' => $article->getCategory()->getSlug(), 'slug'=>$article->getSlug())), 301);

        // Check category
        if($article->getCategory()->getSlug() != $category)
            return $this->redirect($this->generateUrl('blog_article', array('id'=>$article->getId(), 'category' => $article->getCategory()->getSlug(), 'slug'=>$article->getSlug())), 301);

        // View counter
        $view = new View($article, $this->get('session')->getId());
        if($this->getUser() === null){
            $this->em->persist($view);
            $this->em->flush();
        }

        // Comment monitoring
        if($this->getUser() !== null){
            $cm = $this->em->getRepository('NDCBlogBundle:CommentMonitoring')->findOne($article, $this->getUser());

            if($cm === null)
                $cm = new CommentMonitoring($this->getUser(), $article);

            $cm->setLastViewed(new \DateTime());
            $this->em->persist($cm);
            $this->em->flush();
        }

        // Post comment
        $comment = new Comment($article, $this->getUser());
        $form = $this->createForm(new CommentType($this->getUser()), $comment);

        if($request->query->get('r', null) == 'ajax') {
            if($request->isMethod('POST')){
                $form->handleRequest($request);

                if($form->isValid()){
                    if($this->isGranted('ROLE_ADMIN'))
                        $comment->setIsRegistered(true);

                    $this->em->persist($comment);
                    $this->em->flush();
                    
                    return $this->render('@NDCBlog/Blog/_comment.html.twig', array(
                        'comment' => $comment,
                    ));
                }
            }

            $intro_response = count(explode('ERROR: ', $form->getErrors()))-1 > 1 ? '<b>Il y a quelques erreurs dans ce formulaire !</b><br>' : '';
            return new Response($intro_response.str_replace("ERROR: ", "", nl2br($form->getErrors())), 400);
        }

        return array(
            'form' => $form->createView(),
            'view' => $view,
        );
    }

    /**
     * @Template
     */
    public function searchAction(Request $request)
    {
        $query = $request->query->get('q', '');
        $techs = $this->em->getRepository('NDCBlogBundle:Tech')->findAllSlug();
        $categories = $this->em->getRepository('NDCBlogBundle:Category')->findAllSlug();
        $users = $this->em->getRepository('NDCUserBundle:User')->findAllSlug();

        $searchQuery = $this->em->getRepository('NDCBlogBundle:Article')->querySearch($query, $techs, $categories, $users);

        $articles = $this->paginator->paginate(
            $searchQuery,
            $request->query->get('page', 1),
            8
        );

        return array(
            "query" => $query,
            'articles' => $articles,
            'page' => $request->query->get('page', 1),
        );
    }

    /**
     * @Template
     */
    public function demoAction(Demo $demo) {
        // Check if readable
        $article = $demo->getArticle();
        if(empty($article)) {
            if(!$this->isGranted('ROLE_ADMIN'))
                throw $this->createNotFoundException();
        } else {
            $this->isArticleReadable($article);
        }

        return array();
    }

    /**
     * @Template
     */
    public function authorsAction() {
        $authors = $this->em->getRepository('NDCUserBundle:User')->findBy(array("locked" => false, "expired" => false));

        return array(
            "authors" => $authors,
        );
    }

    /**
     * @Template
     */
    public function cguAction()
    {
        return array();
    }

    /**
     * @Template
     */
    public function faqAction()
    {
        return array();
    }

    /**
     * @Template
     */
    public function contactAction(Request $request)
    {
        $contact = new Contact;
        $form = $this->createForm(new ContactType, $contact);

        if($request->isMethod('post')){
            $form->handleRequest($request);

            if($form->isValid()){
                $to = $this->em->getRepository('NDCUserBundle:User')->findContacts();

                $message = \Swift_Message::newInstance()
                    ->setSubject('[NomDeCode] Nouveau message depuis le site web')
                    ->setFrom(array('contact@nomdeco.de' => 'NomDeCode'))
                    ->setTo($to)
                    ->setBody(
                        $this->renderView(
                            'NDCBlogBundle:Blog:email.txt.twig',
                            array(
                                'contact' => $contact,
                                'ip' => $_SERVER['REMOTE_ADDR'],
                            )
                        )
                    )
                ;
                $this->get('mailer')->send($message);

                $this->addFlash('success', 'Le message a bien été envoyé, nous lirons ça sous peu !');

                return $this->redirect($this->generateUrl('blog_contact'));
            }
        }

        return array(
            'form' => $form->createView(),
        );
    }

    private function isArticleReadable($article) {
        if($article->getState() != 'published' || $article->getCreatedAt() > new \DateTime()) {
            if($this->getUser() != $article->getAuthor() and !$this->isGranted('ROLE_ADMIN'))
                if($article->getState() == 'removed')
                    throw new HttpException(410);
                else
                    throw $this->createNotFoundException();
        }

        return true;
    }

    public function setViewSessionIdAction(View $view)
    {
        if($view->getSessionId() != '')
            throw new BadRequestHttpException;

        $view->setSessionId($this->get('session')->getId());
        $this->em->persist($view);
        $this->em->flush();

        return new Response('', 200);
    }
} 

src/NDC/BlogBundle/Resources/views/Blog/_analytics.html.twig
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60612535-1', 'auto');
  ga('send', 'pageview');

</script>

src/NDC/BlogBundle/Resources/views/Blog/_comment.html.twig
 <div id="comment-{{ comment.id }}" class="comment">
	<a {% if comment.isRegistered %}href="{{ path('blog_search', {q: comment.username}) }}"{% endif %}>
		{% set avatar_max = 8 %}
		{% set avatar_number = comment.identifier % (avatar_max - 1) + 1 %}
		<img src="http://www.gravatar.com/avatar/{{ comment.md5 }}?d={{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset('css/img/avatar/'~ avatar_number ~'.png') }}" class="author-img">
	</a>
	<a class="author {% if comment.isRegistered %}author-registered{% endif %}" {% if comment.isRegistered %}href="{{ path('blog_search', {q: comment.username}) }}"{% endif %}>{{ comment.username }}{% if comment.isRegistered %} <i class="fa fa-star" title="Rédacteur"></i>{% endif %}</a>
	<span class="date">{{ comment.createdAt|fullDate }}{% if date(comment.createdAt) > date('-1day') %} à {{ comment.createdAt|date('H:i') }}{% endif %}</span>
	<div class="bulle long-text">{{ comment.message|commentify }}</div>
</div>

src/NDC/BlogBundle/Resources/views/Blog/_preview_article.html.twig
<div class="article_preview">
	{% if is_granted('ROLE_ADMIN') or article.author == app.user %}
		<div class="admin_panel">
			<a href="{{ path('blog_article_admin_edit', { 'id': article.id }) }}"> <i class="fa fa-pencil"></i> Éditer cet article</a>
		</div>
	{% endif %}

	<a href="{{ path('blog_article', { 'id': article.id, category: article.category.slug, 'slug': article.slug }) }}" title="{{ article.title }}">
		<h2>{{ article.title }}</h2>
		<p class="long-text">{{ article.html|stripHTML(250) }}</p>
	</a>
	
	<div class="information muted">
		<a href="{{ path('blog_search', {q: article.author.username}) }}" title="Rédacteur : {{ article.author.username }}">
			<img src="{{ asset(article.author.webPath) }}" class="author-img">
		</a>
		<a class="author" href="{{ path('blog_search', {q: article.author.username}) }}" title="Rédacteur : {{ article.author.username }}">
			<span class="author">{{ article.author.username }}</span>
		</a>
		<span class="date">{{ article.createdAt|fullDate|lower }}</span>
					
		<a class="tech" href="{{ path('blog_search', {q: article.category.slug}) }}" style="background-color:#{{ article.category.color }};color:#{{ article.category.txtColor }};" title="{{ article.category.name }}">{{ article.category.abbr }}</a>
		{% for t in article.tech %}
			<a class="tech tech-framework" href="{{ path('blog_search', {q: t.slug}) }}" style="background-color:#{{ t.color }};color:#{{ t.txtColor }};" title="{{ t.name }}">{{ t.abbr }}</a>
		{% endfor %}
		<span class="comments">{{ article.comments|length }} commentaire{% if article.comments|length > 1 %}s{% endif %}</span>
	</div>
</div>

src/NDC/BlogBundle/Resources/views/Blog/article.html.twig
{% extends '::base.html.twig' %}

{% block title %}{{ article.title }} | {{ parent() }}{% endblock %}

{% block meta %}
	<meta property="og:title" content="{{ article.title }}" />
	<meta property="og:type" content="article" />
	<meta property="article:section" content="{{ article.category.name }}"/>
	<meta property="article:published_time" content="{{ article.createdAt|date('Y-m-d\TH:i:sO') }}"/>
	<meta property="article:modified_time" content="{{ article.updatedAt|date('Y-m-d\TH:i:sO') }}"/>
	<meta name="description" content="{{ article.html|stripHTML(150) }}" />
{% endblock %}

{% block header_class %}article{% endblock %}

{% block header %}
	<div class="top" style="background-color:#{{ article.category.color }};background-image:url({{asset('css/img/bg_category/'~article.category.abbr|lower~'.png')}}), url({{asset('css/img/bg_category/motif_'~article.category.abbr|lower~'.png')}});">
		{% if article.state != "published" or article.createdAt > date("now") %}
			{% if article.state != "published" %}
				{% set article_state = article.state %}
			{% else %}
				{% set article_state = 'future' %}
			{% endif %}
		    {% set states = {
		        'future':  {'icon': 'clock-o', 'info': 'Publication future'},
		        'draft':  {'icon': 'pencil', 'info': 'Cet article est un brouillon'},
		        'removed': {'icon': 'trash-o', 'info': 'Cet article est supprimé'}
		    } %}
		    <div class="mask"></div>
		    <div class="state state-{{ article_state }}">
				<div class="state-icon">
					<i class="fa fa-{{ attribute(states[article_state], 'icon') }}"></i>
				</div>
				<span>{{ attribute(states[article_state], 'info') }}</span>
			</div>
		{% endif %}
	</div>
	<div class="container text">
		<h1>{{ article.title }}</h1>
		<span class="muted">publié {{ article.createdAt|fullDate }}
			{% if article.tech|length > 0 %} - 
				{% for t in article.tech %}
					<a href="{{ path('blog_search', {q: t.slug}) }}">{{ t.name }}</a>
					{% if not loop.last %} + {% endif %}
				{% endfor %}
			{% endif %}
		</span>
	</div>
{% endblock %}

{% block body %}
<article class="long-text">
	{% if article.demo is not null %}
		<a href="{{ path('blog_demo', {id: article.demo.id }) }}" class="lien_demo btn" target="_blank">Voir la démo</a>
	{% endif %}

	{{ article.html|raw }}
</article>
<div class="article-author">
	<div class="container">
			<a class="author" href="{{ path('blog_search', {q: article.author.username}) }}" title="Rédacteur : {{ article.author.username }}">{{ article.author.username }}</a>
			<a href="{{ path('blog_search', {q: article.author.username}) }}" title="Rédacteur : {{ article.author.username }}">
				<img src="{{ asset(article.author.webPath) }}" class="author-img">
			</a>
			{{ helper.author_link(article.author) }}
	</div>
</div>
<section class="comments">
	<div class="container">
		<h1>Commentaires</h1>
		<div class="bulle bulle-top bulle-helper-article">
			<p>Les commentaires se limitent à du <b>texte simple</b> (pas de balise html)</p>
			<p>L'adresse email sera utilisée pour générer un avatar unique et ne sera pas rendue publique.</p>
		</div>
		{{ form(form) }}
		{% for comment in article.comments|reverse %}
			{% include 'NDCBlogBundle:Blog:_comment.html.twig' %}
		{% else %}
			<p data-purpose="help" style="text-align: center;color: white;padding-top: 20px;">Il n'y a pas encore de commentaire sur cet article !</p>
		{% endfor %}
	</div>
</section>
{% endblock %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="{{ asset('css/monokai_sublime.highlight_theme.css') }}">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/ajax-comment.js') }}"></script>
    <script src="{{ asset('js/highlight.pack.js') }}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    {% if not app.user and view.sessionId is empty %}
        <script type="text/javascript">
            $(function(){
                $.get('{{ path('blog_set_view_session_id', {id:view.id}) }}');
            });
        </script>
    {% endif %}
{% endblock %}

src/NDC/BlogBundle/Resources/views/Blog/authors.html.twig
{% extends '::base.html.twig' %}

{% block title %}Rédacteurs | {{ parent() }}{% endblock %}

{% block body %}
<section class="container spacer">
	<h1>Rédacteurs</h1>
	{% for author in authors %}
		<div class="article-author list-authors">
			<div class="container">
					<a href="{{ path('blog_search', {q: author.username}) }}" class="author" title="Rédacteur : {{ author.username }}">{{ author.username }}</a>
					<a href="{{ path('blog_search', {q: author.username}) }}" title="Rédacteur : {{ author.username }}">
						<img src="{{ asset(author.webPath) }}" class="author-img">
					</a>
					<p>{{ author.desc|raw }}</p>
					{{ helper.author_link(author) }}
			</div>
		</div>
	{% endfor %}
</section>
{% endblock %}

src/NDC/BlogBundle/Resources/views/Blog/comment.html.twig
<div class="comment">
	<a>
		{% set avatar_max = 8 %}
		{% set avatar_number = comment.identifier % (avatar_max - 1) + 1 %}
		<img src="http://www.gravatar.com/avatar/{{ comment.md5 }}?d={{ app.request.scheme ~'://' ~ app.request.httpHost ~ asset('css/img/avatar/'~ avatar_number ~'.png') }}" class="author-img">
	</a>
	<a class="author {% if comment.isRegistered %}author-registered{% endif %}">{{ comment.username }}{% if comment.isRegistered %} <i class="fa fa-star" title="Rédacteur"></i>{% endif %}</a>
	<span class="date">{{ comment.createdAt|fullDate }}{% if date(comment.createdAt) > date('-1day') %} à {{ comment.createdAt|date('H:i') }}{% endif %}</span>
	<div class="bulle long-text">{{ comment.message|commentify }}</div>
</div>

src/NDC/BlogBundle/Resources/views/Blog/contact.html.twig
{% extends '::base.html.twig' %}

{% block title %}Nous contacter | {{ parent() }}{% endblock %}

{% block body %}
    <section class="container spacer">
        <h1>Nous contacter</h1>

        {% for label, flashes in app.session.flashbag.all %}
	        {% for flash in flashes %}
	        	<p style="color:#4EB56E;"><i class="fa fa-check"></i> {{ flash }}</p>
	        {% endfor %}
	    {% endfor %}

		{{ form_start(form, {'attr': {'class': 'form-classic'}}) }}
	    	{{ form_widget(form) }}
	    {{ form_end(form) }}

    </section>
{% endblock %}

src/NDC/BlogBundle/Resources/views/Blog/demo.html.twig
<html>
	{% set demo_dependencies = demo.dependencies|split('\r\n') %}

    <head>
        <meta charset="UTF-8" />
        <meta name="language" content="fr-FR" />
        <meta property="og:locale" content="fr_FR" />
        <title>{% block title %}Démo{% if demo.article is not null %} : {{ demo.article.title|capitalize}}{% endif %} | Nomdecode{% endblock %}</title>
            
        <style>
		body {
			margin:0;
			padding-top:6vh;
			font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
			font-size: 14px;
		}
        </style>

        {% block stylesheets %}
			{% for c in demo_dependencies if c|split('.')|last == 'css' %}
				<link rel="stylesheet" href="{{ c }}">
			{% endfor %}
			<style>{{ demo.css|raw }}</style>
        {% endblock %}
        <link rel="icon" type="image/png" href="{{ asset('css/img/favicon.png') }}" />
    </head>
    <body>
    	<section style="display: table;margin: auto;">
    		{{ demo.html|raw }}	
    	</section>

		<script src="{{ asset('js/jquery.min.js') }}"></script>
		{% for c in demo_dependencies if c|split('.')|last == 'js' %}
			<script src="{{ c }}"></script>
		{% endfor %}
		<script>{{ demo.js|raw }}</script>
    </body>
</html>

src/NDC/BlogBundle/Resources/views/Blog/email.txt.twig
Expéditeur : {{ contact.from }}
Envoyé le : {{ contact.createdAt|date('d/m/Y à H:i') }}
Adresse IP : {{ ip }}

Message :
{{ contact.message }}

src/NDC/BlogBundle/Resources/views/Blog/preview_article.html.twig
<div class="article_preview">
	{% if is_granted('ROLE_ADMIN') or article.author == app.user %}
		<div class="admin_panel">
			<a href="{{ path('blog_article_admin_edit', { 'id': article.id }) }}"> <i class="fa fa-pencil"></i> Éditer cet article</a>
		</div>
	{% endif %}

	<a href="{{ path('blog_article', { 'id': article.id, 'slug': article.slug }) }}" title="{{ article.title|capitalize }}">
		<h2>{{ article.title|capitalize }}</h2>
		<p class="long-text">{{ article.html|striptags|slice(0, 250)|raw }}{% if article.html|striptags|length|raw > 250 %}...{% endif %}</p>
	</a>
	
	<div class="information muted">
		<a title="Rédacteur : {{ article.author.username }}">
			<img src="{{ asset(article.author.webPath) }}" class="author-img">
		</a>
		<a class="author" title="Rédacteur : {{ article.author.username }}">
			<span class="author">{{ article.author.username }}</span>
		</a>
		<span class="date">{{ article.createdAt|fullDate|lower }}</span>
					
		<a class="tech" style="background-color:#{{ article.category.color }};color:#{{ article.category.txtColor }};" title="{{ article.category.name }}">{{ article.category.abbr }}</a>
		{% for t in article.tech %}
			<a class="tech tech-framework" style="background-color:#{{ t.color }};color:#{{ t.txtColor }};" title="{{ t.name }}">{{ t.abbr }}</a>
		{% endfor %}
		<span class="comments">{{ article.comments|length }} commentaire{% if article.comments|length > 1 %}s{% endif %}</span>
	</div>
</div>

src/NDC/BlogBundle/Resources/views/Blog/search.html.twig
{% extends '::base.html.twig' %}

{% block body %}
<section class="container spacer">
	<h1>Résultats de la recherche : "{{ query }}"</h1>
	<br/>
	{% for article in articles %}
		{% include 'NDCBlogBundle:Blog:_preview_article.html.twig' %}
	{% endfor %}

	{{ helper.pagination(page, articles.pageCount, 'blog_search', {'q': query}) }}
</section>
{% endblock %}